language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install "pillow" "numpy" "texttable" "matplotlib" "pandas" "cuitools==1.7.2.6" "prompt-toolkit>3.0" "pyfiglet" "python-dateutil"
script:
  - python setup.py install
